services:
  agenda:
    container_name: agenda
    restart: unless-stopped
    build:
      context: ./agenda
      dockerfile: Dockerfile
    networks:
      - caddy
    labels:
      caddy: agenda.ophap.com
      caddy.reverse_proxy: "{{upstreams 8080}}"

  recognizers:
    image: qnduong/recognizers:1.0
    container_name: recognizers
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: recognizers.ophap.com
      caddy.reverse_proxy: "{{upstreams 8080}}"

  lisa:
    container_name: lisa
    image: qnduong/lisa:1.0
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=
      - RECOGNIZERS_BASE_URL=http://recognizers:8080
      - AGENDA_BASE_URL=http://agenda:8080
      - MODEL_NAME=gpt-4o-mini
    networks:
      - caddy
    labels:
      caddy: lisa.ophap.com
      caddy.reverse_proxy: "{{upstreams 8080}}"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy/config:/config/caddy
      - ./caddy/data:/data

networks:
  caddy:
    external: true
